export const metadata: Metadata = {
  title: 'Pagina di prova da Layout Prova 01',
  description: 'Generated by create next app',
};

const ProvaLayout = ({ children }) => {
  return <div>{children}</div>;
};
export default ProvaLayout;
