export const metadata: Metadata = {
  title: 'Pagina di prova',
  description: 'Generated by create next app',
};

const ProvaPage = () => {
  return <div>ProvaPage</div>;
};

export default ProvaPage;
